# The relay can also be used to dual write data to Kapacitor
#
# There are a few advantages of using the relay instead of relying on InfluxDB subscriptions
#
# 1. Traffic is HTTP/TCP meaning you don't have to worry about dropped UDP packets
# 2. Less load on InfluxDB since it doesn't have to fork the data.
# 3. Slighly lower latency since there is one less hop.
#
# Kapacitor is wire compatible with InfluxDB for writes.
# This means you can add a Kapacitor instance to the output list as if it were an InfluxDB instance.
#


# This example config sends all writes to
# two InfluxDB hosts and a single Kapacitor host.
[[http]]
name = "kapacitor-http"
bind-addr = "0.0.0.0:9096"
default-retention-policy = "autogen"
output = [
    { name="influxdb1", location = "http://influxdb1:8086/write" },
    { name="influxdb2", location = "http://influxdb2:8086/write" },
    { name="kapacitor1", location = "http://kapacitor1:9092/write" },
]
