

[[http]]
name = "example-http"
bind-addr = "192.168.128.129:9096"
output = [
    { name="local1", location = "http://172.17.0.3:8086/write" },
    { name="local2", location = "http://172.17.0.2:8086/write" },
]

[[udp]]
name = "example-udp"
bind-addr = "192.168.128.129:9096"
read-buffer = 0 # default
output = [
    { name="local1", location="127.0.0.1:8089", mtu=512 },
    { name="local2", location="127.0.0.1:7089", mtu=1024 },
]
